{
 "title": "Lab@Home Measurements",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "DHT Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Lab@Home_Measurements\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Kessel Temperature (IST)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Lab@Home_Measurements\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._field == \"kesseltemperatureist\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "DHT Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Lab@Home_Measurements\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Kessel Temperature (Soll)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Lab@Home_Measurements\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._field == \"kesseltemperaturesoll\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Party Temperature (Soll)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"Lab@Home_Measurements\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._field == \"partytemperaturesoll\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Sparbetrieb",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"Lab@Home_Measurements\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._field == \"sparbetrieb\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  },
  {
   "title": "Betriebsart",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"Lab@Home_Measurements\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._field == \"betriebsart\")\r\n  |> yield(name: \"_results\")"
    }
   ]
  }
 ]
}